name: Tu Dong Build APK Cordova
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-22.04 # Giữ nguyên Ubuntu 22.04 siêu ổn định
    steps:
    - name: Checkout Ma Nguon
      uses: actions/checkout@v4

    - name: Cai dat Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cai dat Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 

    - name: Cai dat Apache Cordova CLI
      run: |
        npm install -g cordova
        # ĐÃ XÓA LỆNH TELEMETRY Ở ĐÂY ĐỂ TRÁNH SẬP LỖI

    - name: Khoi tao du an va nap du lieu
      run: |
        cordova create temp_app com.pctuyenquang.airgap "AirGapSCADA"
        rm -rf temp_app/www/*
        
        cp index.html temp_app/www/index.html
        cp manifest.json temp_app/www/manifest.json || true
        cp sw.js temp_app/www/sw.js || true
        cp config.xml temp_app/config.xml || true

    - name: Cai dat Plugin ho tro Camera va Tai File an toan
      run: |
        cd temp_app
        cordova plugin add cordova-plugin-camera
        cordova plugin add cordova-plugin-file
        cordova plugin add cordova-plugin-x-socialsharing
        
    - name: Xay dung nen tang Android va Bien dich APK
      run: |
        cd temp_app
        cordova platform add android@13.0.0
        cordova build android --debug

    - name: Xuat file APK thanh pham de tai ve
      uses: actions/upload-artifact@v4
      with:
        name: AirGap_Receiver_PC_TuyenQuang
        path: temp_app/platforms/android/app/build/outputs/apk/debug/Air-GapSCADA.apk
